# tickets/staff_data.py

STAFF_LIST = [
    {'id': 1, 'name': 'Noel E. Reyes', 'expertise': ['MANAGEMENT', 'SYSTEM ADMIN', 'ALL']},
    {'id': 2, 'name': 'Marvin M. Cruz', 'expertise': ['CCTV']},
    {'id': 3, 'name': 'Ariel C. Samosino', 'expertise': ['CCTV']},
    {'id': 4, 'name': 'Elison D. Carredo', 'expertise': ['CCTV']},
    {'id': 5, 'name': 'Rolando O. De Castro Jr.', 'expertise': ['CCTV']},
    {'id': 6, 'name': 'Edgar Manalansan', 'expertise': ['CCTV']},
    {'id': 7, 'name': 'Ariel Cariaga', 'expertise': ['CCTV']},
    {'id': 8, 'name': 'Ike Joseph P. Lumaad', 'expertise': ['WEBSITE', 'SYSTEM DEV']},
    {'id': 9, 'name': 'Niel Ian I. Pariñas', 'expertise': ['WEBSITE', 'SYSTEM DEV']},
    {'id': 10, 'name': 'Zandro S. Ocampo', 'expertise': ['NETWORK', 'INTERNET']},
    {'id': 11, 'name': 'Reagan James H. Tayag', 'expertise': ['NETWORK', 'INTERNET']},
    {'id': 12, 'name': 'Erickson J. Galvez', 'expertise': ['NETWORK', 'INTERNET']},
    {'id': 13, 'name': 'Edelfonso D. Orig I', 'expertise': ['NETWORK', 'INTERNET']},
    {'id': 14, 'name': 'Marbie A. Sumbe', 'expertise': ['NETWORK', 'INTERNET']},
    {'id': 15, 'name': 'Karenshene SD. Malvar', 'expertise': ['ACCOUNT', 'SOFTWARE', 'SECURITY']},
    {'id': 16, 'name': 'Allenn Raphael F. Gutierrez', 'expertise': ['ACCOUNT', 'SOFTWARE', 'SECURITY']},
    {'id': 17, 'name': 'Jona A. Siarot', 'expertise': ['GRAPHICS', 'MULTIMEDIA']},
    {'id': 18, 'name': 'Jerus L. De Jesus', 'expertise': ['GRAPHICS', 'MULTIMEDIA']},
    {'id': 19, 'name': 'Julian G. Uy', 'expertise': ['PC MAINTENANCE', 'PRINTER', 'HARDWARE']},
    {'id': 20, 'name': 'Mark Joseph C. Sotto', 'expertise': ['PC MAINTENANCE', 'PRINTER', 'HARDWARE']},
    {'id': 21, 'name': 'Sergio Paulo B. Leoncio', 'expertise': ['PC MAINTENANCE', 'PRINTER', 'HARDWARE']},
    {'id': 22, 'name': 'Aquilles S. Capili', 'expertise': ['PC MAINTENANCE', 'PRINTER', 'HARDWARE']},
    {'id': 23, 'name': 'Mark Anthony G. De Guzman', 'expertise': ['PC MAINTENANCE', 'PRINTER', 'HARDWARE']},
    {'id': 24, 'name': 'Raffy R. Del Rosario', 'expertise': ['PC MAINTENANCE', 'PRINTER', 'HARDWARE']},
    {'id': 25, 'name': 'Roel D. Tilo', 'expertise': ['PC MAINTENANCE', 'PRINTER', 'HARDWARE']},
    {'id': 26, 'name': 'Bernie L. De Jesus', 'expertise': ['PC MAINTENANCE', 'PRINTER', 'HARDWARE']},
    {'id': 27, 'name': 'Genesis De Leon Flores', 'expertise': ['PC MAINTENANCE', 'PRINTER', 'HARDWARE']},
    {'id': 28, 'name': 'Christian Angelo A. Navera', 'expertise': ['PC MAINTENANCE', 'PRINTER', 'HARDWARE']},
    {'id': 29, 'name': 'Alvin John Villaseñor', 'expertise': ['PC MAINTENANCE', 'PRINTER', 'HARDWARE']},
    {'id': 30, 'name': 'Juan Pedro', 'expertise': ['SYSTEM TESTING']},
]
