# Generated by Django 6.0.2 on 2026-03-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('school_id', models.CharField(max_length=50, unique=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
