# Generated by Django 6.0.2 on 2026-03-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date the ticket is scheduled for', null=True),
        ),
    ]
