# Generated by Django 6.0.2 on 2026-02-24 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='school_district',
            field=models.CharField(blank=True, choices=[('DISTRICT_I', 'District I - Arkong Bato'), ('DISTRICT_II', 'District II - Balangkas'), ('DISTRICT_III', 'District III - Karuhatan'), ('DISTRICT_IV', 'District IV - Malinta'), ('DISTRICT_V', 'District V - Marulas')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='support_type',
            field=models.CharField(blank=True, choices=[('MS_ACCOUNT', 'Creation of Microsoft Account'), ('GOOGLE_ACCOUNT', 'Creation of Google Account'), ('PASSWORD_RESET', 'Password Reset for Microsoft or Google Account'), ('PC_MAINTENANCE', 'Computer Maintenance/Check-Up or Repair Request'), ('NETWORK_MAINTENANCE', 'Computer Network Maintenance/Check-Up or Repair Request'), ('SOFTWARE_APP', 'Software Application Assessment/Installation Request'), ('DIGITAL_AUTO', 'Digital Automation Assessment and Request'), ('CCTV', 'CCTV Maintenance/Check-Up or Repair Request'), ('OTHER', 'Other Support')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(help_text='Request Details'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.project'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'In Review'), ('DONE', 'Done')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
