# Generated by Django 6.0.2 on 2026-04-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('PENDING_ACCEPTANCE', 'Pending Acceptance'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('UNRESOLVED', 'Unresolved'), ('RESOLVED', 'Resolved'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
