# Generated by Django 6.0.2 on 2026-02-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_contact_number_ticket_email_ticket_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for ICT Unit', null=True),
        ),
    ]
