# Generated by Django 6.0.2 on 2026-03-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('UNRESOLVED', 'Unresolved'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
