# Generated by Django 6.0.2 on 2026-02-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='predicted_hours',
            field=models.IntegerField(blank=True, help_text='AI estimated resolution time in hours', null=True),
        ),
    ]
