# Generated by Django 6.0.2 on 2026-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Time the ticket is scheduled for', null=True),
        ),
    ]
