# Generated by Django 6.0.2 on 2026-04-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1200000$yxVstmeDa4jgFPKbARyyYt$TYZVP2LaT6q3jtk6FzUV75dzoGUi4DD+7LfmWAAsrlE=', max_length=128),
        ),
    ]
