# Generated by Django 6.0.2 on 2026-03-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, help_text='Comma-separated skills (e.g., CCTV, NETWORK, PC_MAINTENANCE)', max_length=255),
        ),
    ]
