# Generated by Django 6.0.2 on 2026-03-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_user_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Date the ticket is scheduled for', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('PENDING_ACCEPTANCE', 'Pending Acceptance'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('UNRESOLVED', 'Unresolved'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
