# Generated by Django 6.0.2 on 2026-04-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_school_ict_contact_number_school_ict_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='ticket',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, help_text='End time the ticket is scheduled for', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, help_text='Start time the ticket is scheduled for', null=True),
        ),
    ]
