# Generated by Django 6.0.2 on 2026-04-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_attachment',
            field=models.FileField(blank=True, null=True, upload_to='resolutions/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('PENDING_ACCEPTANCE', 'Pending Acceptance'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('UNRESOLVED', 'Unresolved'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
