# Generated by Django 6.0.2 on 2026-04-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_resolution_attachment_ticket_resolution_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_id', models.CharField(max_length=50)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('ict_name', models.CharField(help_text='Full name of the ICT Coordinator', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('domain_verified', models.BooleanField(default=False, help_text='Auto-flagged if email ends with @deped.gov.ph')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
