# Generated by Django 6.0.2 on 2026-04-26 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_schoolaccountrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolaccountrequest',
            name='district',
        ),
        migrations.RemoveField(
            model_name='schoolaccountrequest',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='schoolaccountrequest',
            name='school_name',
        ),
        migrations.AddField(
            model_name='schoolaccountrequest',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_requests', to='tickets.school'),
            preserve_default=False,
        ),
    ]
