# Generated by Django 6.0.2 on 2026-04-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetRequest',
        ),
    ]
