# Generated by Django 6.0.2 on 2026-04-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_delete_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('PENDING_ACCEPTANCE', 'Pending Acceptance'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('UNRESOLVED', 'Unresolved'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
    ]
