# Generated by Django 6.0.2 on 2026-05-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_ticket_end_date_ticket_predicted_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('PENDING_ACCEPTANCE', 'Pending Acceptance'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('UNRESOLVED', 'Unresolved'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
