# Generated by Django 6.0.2 on 2026-05-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_ticket_created_at_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client_signature',
            field=models.TextField(blank=True, help_text='Base64-encoded client signature image', null=True),
        ),
    ]
