# Generated by Django 6.0.2 on 2026-05-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticket_client_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_changed_password',
            field=models.BooleanField(default=False, help_text='Set to True after the user changes or dismisses the default password prompt.'),
        ),
    ]
