# Generated by Django 6.0.2 on 2026-05-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_user_has_changed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_tasks_done',
            field=models.IntegerField(default=0),
        ),
    ]
