# Generated by Django 6.0.2 on 2026-08-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_passwordresetotp_user_alter_passwordresetotp_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the ticket was assigned to staff', null=True),
        ),
    ]
