# Generated by Django 6.0.2 on 2026-09-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_ticket_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='signed_jrf_attachment',
            field=models.FileField(blank=True, help_text='Scanned or photographed physically signed JRF', null=True, upload_to='signed_jrfs/'),
        ),
    ]
